import '../features/members/models/member_model.dart';

final List<Member> dummyMembers = [
  Member(
    id: '1',
    memberCode: 'GYM-2026-0001',
    name: 'Arjun Sharma',
    phone: '9876543210',
    email: 'arjun.sharma@email.com',
    dateOfBirth: DateTime(1995, 5, 15),
    gender: 'Male',
    planName: 'Annual Elite',
    planPrice: 15000,
    status: MemberStatus.active,
    joinDate: DateTime(2025, 1, 10),
    planExpiry: DateTime(2026, 1, 10),
    assignedTrainerId: 'trn_001',
    assignedTrainerName: 'Sneha Kapoor',
    bloodGroup: 'O+',
    address: 'Andheri West, Mumbai',
    emergencyContactName: 'Rajesh Sharma',
    emergencyContactPhone: '9876543211',
    branch: 'Branch A',
  ),
  Member(
    id: '2',
    memberCode: 'GYM-2026-0002',
    name: 'Priya Patel',
    phone: '9123456789',
    email: 'priya.patel@email.com',
    dateOfBirth: DateTime(1998, 8, 22),
    gender: 'Female',
    planName: 'Monthly Standard',
    planPrice: 2000,
    status: MemberStatus.active,
    joinDate: DateTime(2026, 3, 5),
    planExpiry: DateTime(2026, 4, 5),
    assignedTrainerId: 'trn_001',
    assignedTrainerName: 'Sneha Kapoor',
    bloodGroup: 'A+',
    address: 'Satellite, Ahmedabad',
    emergencyContactName: 'Dinesh Patel',
    emergencyContactPhone: '9123456780',
    branch: 'Branch A',
  ),
  Member(
    id: '3',
    memberCode: 'GYM-2026-0003',
    name: 'Rohan Gupta',
    phone: '9988776655',
    email: 'rohan.gupta@email.com',
    dateOfBirth: DateTime(1992, 12, 10),
    gender: 'Male',
    planName: 'Quarterly Premium',
    planPrice: 5500,
    status: MemberStatus.active,
    joinDate: DateTime(2026, 2, 15),
    planExpiry: DateTime(2026, 5, 15),
    assignedTrainerId: 'trn_other',
    assignedTrainerName: 'Rahul Mehta',
    bloodGroup: 'B+',
    address: 'Indiranagar, Bangalore',
    emergencyContactName: 'Suresh Gupta',
    emergencyContactPhone: '9988776654',
    branch: 'Branch A',
  ),
  Member(
    id: '4',
    memberCode: 'GYM-2026-0004',
    name: 'Ananya Iyer',
    phone: '9444556677',
    email: 'ananya.iyer@email.com',
    dateOfBirth: DateTime(2000, 4, 30),
    gender: 'Female',
    planName: 'Monthly Basic',
    planPrice: 1500,
    status: MemberStatus.expired,
    joinDate: DateTime(2025, 12, 1),
    planExpiry: DateTime(2026, 1, 1),
    assignedTrainerId: 'trn_001',
    assignedTrainerName: 'Sneha Kapoor',
    bloodGroup: 'O-',
    address: 'Adyar, Chennai',
    emergencyContactName: 'Venkatesh Iyer',
    emergencyContactPhone: '9444556678',
    branch: 'Branch A',
  ),
  Member(
    id: '5',
    memberCode: 'GYM-2026-0005',
    name: 'Vikram Singh',
    phone: '9000112233',
    email: 'vikram.singh@email.com',
    dateOfBirth: DateTime(1988, 2, 14),
    gender: 'Male',
    planName: 'Annual Elite',
    planPrice: 15000,
    status: MemberStatus.active,
    joinDate: DateTime(2025, 6, 20),
    planExpiry: DateTime(2026, 6, 20),
    assignedTrainerId: 'trn_other',
    assignedTrainerName: 'Rahul Mehta',
    bloodGroup: 'AB+',
    address: 'Malviya Nagar, Delhi',
    emergencyContactName: 'Karan Singh',
    emergencyContactPhone: '9000112234',
    branch: 'Branch A',
  ),
  Member(
    id: '6',
    memberCode: 'GYM-2026-0006',
    name: 'Sanya Malhotra',
    phone: '9555667788',
    email: 'sanya.m@email.com',
    dateOfBirth: DateTime(1996, 7, 5),
    gender: 'Female',
    planName: 'Monthly Standard',
    planPrice: 2000,
    status: MemberStatus.paused,
    joinDate: DateTime(2026, 1, 10),
    planExpiry: DateTime(2026, 2, 10),
    assignedTrainerId: 'trn_001',
    assignedTrainerName: 'Sneha Kapoor',
    bloodGroup: 'B-',
    address: 'Bandra West, Mumbai',
    emergencyContactName: 'Ravi Malhotra',
    emergencyContactPhone: '9555667789',
    branch: 'Branch A',
  ),
  Member(
    id: '7',
    memberCode: 'GYM-2026-0007',
    name: 'Kabir Das',
    phone: '9222334455',
    email: 'kabir.das@email.com',
    dateOfBirth: DateTime(1990, 10, 12),
    gender: 'Male',
    planName: 'Quarterly Premium',
    planPrice: 5500,
    status: MemberStatus.active,
    joinDate: DateTime(2026, 4, 1),
    planExpiry: DateTime(2026, 7, 1),
    assignedTrainerId: 'trn_other',
    assignedTrainerName: 'Rahul Mehta',
    bloodGroup: 'A-',
    address: 'Salt Lake, Kolkata',
    emergencyContactName: 'Meera Das',
    emergencyContactPhone: '9222334456',
    branch: 'Branch A',
  ),
  Member(
    id: '8',
    memberCode: 'GYM-2026-0008',
    name: 'Ishaan Khattar',
    phone: '9333445566',
    email: 'ishaan.k@email.com',
    dateOfBirth: DateTime(1997, 1, 25),
    gender: 'Male',
    planName: 'Monthly Basic',
    planPrice: 1500,
    status: MemberStatus.active,
    joinDate: DateTime(2026, 5, 1),
    planExpiry: DateTime(2026, 6, 1),
    assignedTrainerId: null,
    assignedTrainerName: null,
    bloodGroup: 'O+',
    address: 'Juhu, Mumbai',
    emergencyContactName: 'Neelam Khattar',
    emergencyContactPhone: '9333445567',
    branch: 'Branch A',
  ),
  Member(
    id: '9',
    memberCode: 'GYM-2026-0009',
    name: 'Zoya Akhtar',
    phone: '9777889900',
    email: 'zoya.a@email.com',
    dateOfBirth: DateTime(1994, 3, 18),
    gender: 'Female',
    planName: 'Annual Elite',
    planPrice: 15000,
    status: MemberStatus.active,
    joinDate: DateTime(2025, 11, 15),
    planExpiry: DateTime(2026, 11, 15),
    assignedTrainerId: 'trn_001',
    assignedTrainerName: 'Sneha Kapoor',
    bloodGroup: 'B+',
    address: 'Cuffe Parade, Mumbai',
    emergencyContactName: 'Javed Akhtar',
    emergencyContactPhone: '9777889901',
    branch: 'Branch A',
  ),
  Member(
    id: '10',
    memberCode: 'GYM-2026-0010',
    name: 'Aditya Roy',
    phone: '9666778899',
    email: 'aditya.roy@email.com',
    dateOfBirth: DateTime(1993, 11, 30),
    gender: 'Male',
    planName: 'Monthly Standard',
    planPrice: 2000,
    status: MemberStatus.active,
    joinDate: DateTime(2026, 2, 20),
    planExpiry: DateTime(2026, 3, 20),
    assignedTrainerId: 'trn_other',
    assignedTrainerName: 'Rahul Mehta',
    bloodGroup: 'A+',
    address: 'Worli, Mumbai',
    emergencyContactName: 'Salome Roy',
    emergencyContactPhone: '9666778890',
    branch: 'Branch A',
  ),
  Member(
    id: '11',
    memberCode: 'GYM-2026-0011',
    name: 'Kriti Sanon',
    phone: '9888990011',
    email: 'kriti.s@email.com',
    dateOfBirth: DateTime(1995, 7, 27),
    gender: 'Female',
    planName: 'Quarterly Premium',
    planPrice: 5500,
    status: MemberStatus.active,
    joinDate: DateTime(2026, 1, 5),
    planExpiry: DateTime(2026, 4, 5),
    assignedTrainerId: null,
    assignedTrainerName: null,
    bloodGroup: 'AB-',
    address: 'Lokhandwala, Mumbai',
    emergencyContactName: 'Rahul Sanon',
    emergencyContactPhone: '9888990012',
    branch: 'Branch A',
  ),
  Member(
    id: '12',
    memberCode: 'GYM-2026-0012',
    name: 'Varun Dhawan',
    phone: '9999001122',
    email: 'varun.d@email.com',
    dateOfBirth: DateTime(1992, 4, 24),
    gender: 'Male',
    planName: 'Monthly Basic',
    planPrice: 1500,
    status: MemberStatus.expired,
    joinDate: DateTime(2025, 10, 10),
    planExpiry: DateTime(2025, 11, 10),
    assignedTrainerId: 'trn_other',
    assignedTrainerName: 'Rahul Mehta',
    bloodGroup: 'O+',
    address: 'Juhu, Mumbai',
    emergencyContactName: 'David Dhawan',
    emergencyContactPhone: '9999001123',
    branch: 'Branch A',
  ),
  Member(
    id: '13',
    memberCode: 'GYM-2026-0013',
    name: 'Sara Ali Khan',
    phone: '9111223344',
    email: 'sara.ak@email.com',
    dateOfBirth: DateTime(1999, 8, 12),
    gender: 'Female',
    planName: 'Annual Elite',
    planPrice: 15000,
    status: MemberStatus.active,
    joinDate: DateTime(2025, 9, 20),
    planExpiry: DateTime(2026, 9, 20),
    assignedTrainerId: 'trn_001',
    assignedTrainerName: 'Sneha Kapoor',
    bloodGroup: 'B+',
    address: 'Amrita Shergill Marg, Delhi',
    emergencyContactName: 'Saif Ali Khan',
    emergencyContactPhone: '9111223345',
    branch: 'Branch B',
  ),
  Member(
    id: '14',
    memberCode: 'GYM-2026-0014',
    name: 'Ranbir Kapoor',
    phone: '9222445566',
    email: 'ranbir.k@email.com',
    dateOfBirth: DateTime(1987, 9, 28),
    gender: 'Male',
    planName: 'Monthly Standard',
    planPrice: 2000,
    status: MemberStatus.active,
    joinDate: DateTime(2026, 4, 15),
    planExpiry: DateTime(2026, 5, 15),
    assignedTrainerId: 'trn_001',
    assignedTrainerName: 'Sneha Kapoor',
    bloodGroup: 'A+',
    address: 'Pali Hill, Mumbai',
    emergencyContactName: 'Rishi Kapoor',
    emergencyContactPhone: '9222445567',
    branch: 'Branch B',
  ),
  Member(
    id: '15',
    memberCode: 'GYM-2026-0015',
    name: 'Deepika Padukone',
    phone: '9333556677',
    email: 'deepika.p@email.com',
    dateOfBirth: DateTime(1991, 1, 5),
    gender: 'Female',
    planName: 'Quarterly Premium',
    planPrice: 5500,
    status: MemberStatus.active,
    joinDate: DateTime(2026, 3, 10),
    planExpiry: DateTime(2026, 6, 10),
    assignedTrainerId: 'trn_001',
    assignedTrainerName: 'Sneha Kapoor',
    bloodGroup: 'O+',
    address: 'Prabhadevi, Mumbai',
    emergencyContactName: 'Prakash Padukone',
    emergencyContactPhone: '9333556678',
    branch: 'Branch B',
  ),
  Member(
    id: '16',
    memberCode: 'GYM-2026-0016',
    name: 'Ayushmann Khurrana',
    phone: '9444667788',
    email: 'ayushmann.k@email.com',
    dateOfBirth: DateTime(1989, 9, 14),
    gender: 'Male',
    planName: 'Monthly Basic',
    planPrice: 1500,
    status: MemberStatus.paused,
    joinDate: DateTime(2026, 1, 20),
    planExpiry: DateTime(2026, 2, 20),
    assignedTrainerId: null,
    assignedTrainerName: null,
    bloodGroup: 'B-',
    address: 'Panchkula, Chandigarh',
    emergencyContactName: 'P. Khurrana',
    emergencyContactPhone: '9444667789',
    branch: 'Branch B',
  ),
  Member(
    id: '17',
    memberCode: 'GYM-2026-0017',
    name: 'Alia Bhatt',
    phone: '9555778899',
    email: 'alia.b@email.com',
    dateOfBirth: DateTime(1998, 3, 15),
    gender: 'Female',
    planName: 'Annual Elite',
    planPrice: 15000,
    status: MemberStatus.active,
    joinDate: DateTime(2025, 12, 5),
    planExpiry: DateTime(2026, 12, 5),
    assignedTrainerId: null,
    assignedTrainerName: null,
    bloodGroup: 'A-',
    address: 'Juhu, Mumbai',
    emergencyContactName: 'Mahesh Bhatt',
    emergencyContactPhone: '9555778890',
    branch: 'Branch B',
  ),
  Member(
    id: '18',
    memberCode: 'GYM-2026-0018',
    name: 'Vicky Kaushal',
    phone: '9666889900',
    email: 'vicky.k@email.com',
    dateOfBirth: DateTime(1993, 5, 16),
    gender: 'Male',
    planName: 'Monthly Standard',
    planPrice: 2000,
    status: MemberStatus.active,
    joinDate: DateTime(2026, 5, 5),
    planExpiry: DateTime(2026, 6, 5),
    assignedTrainerId: null,
    assignedTrainerName: null,
    bloodGroup: 'O+',
    address: 'Andheri, Mumbai',
    emergencyContactName: 'Sham Kaushal',
    emergencyContactPhone: '9666889901',
    branch: 'Branch B',
  ),
  Member(
    id: '19',
    memberCode: 'GYM-2026-0019',
    name: 'Taapsee Pannu',
    phone: '9777990011',
    email: 'taapsee.p@email.com',
    dateOfBirth: DateTime(1992, 8, 1),
    gender: 'Female',
    planName: 'Quarterly Premium',
    planPrice: 5500,
    status: MemberStatus.inactive,
    joinDate: DateTime(2025, 8, 15),
    planExpiry: DateTime(2025, 11, 15),
    assignedTrainerId: null,
    assignedTrainerName: null,
    bloodGroup: 'B+',
    address: 'Ludhiana, Punjab',
    emergencyContactName: 'Dilmohan Pannu',
    emergencyContactPhone: '9777990012',
    branch: 'Branch B',
  ),
  Member(
    id: '20',
    memberCode: 'GYM-2026-0020',
    name: 'Rajkummar Rao',
    phone: '9888001122',
    email: 'rajkummar.r@email.com',
    dateOfBirth: DateTime(1989, 8, 31),
    gender: 'Male',
    planName: 'Monthly Basic',
    planPrice: 1500,
    status: MemberStatus.expired,
    joinDate: DateTime(2025, 7, 1),
    planExpiry: DateTime(2025, 8, 1),
    assignedTrainerId: null,
    assignedTrainerName: null,
    bloodGroup: 'AB+',
    address: 'Gurgaon, Haryana',
    emergencyContactName: 'Kamlesh Yadav',
    emergencyContactPhone: '9888001123',
    branch: 'Branch B',
  ),
];
